// GENERATED CODE - DO NOT MODIFY BY HAND

/// English translation map for the monitor dashboard.
const Map<String, String> enTranslations = {
  'tabTimeline': 'TIMELINE',
  'tabRequest': 'REQUEST',
  'tabResponse': 'RESPONSE',
  'tabHeaders': 'HEADERS',
  'initLabel': 'LOAD',
  'actionLabel': 'INTERACTION',
  'screensTitle': 'Screens',
  'allScreens': 'All Screens',
  'unknownScreen': 'Unknown Screen',
  'samples': 'samples',
  'fpsHistory': 'FPS HISTORY',
  'ramHistory': 'RAM HISTORY',
  'noApiCalls': 'No API calls yet',
  'onThisScreen': 'on this screen',
  'noErrors': 'No Flutter errors',
  'caughtYet': 'caught yet',
  'filterAll': 'ALL',
  'filterSlow': 'SLOW',
  'filterError': 'ERR',
  'searchPlaceholder': 'Search by URL, Method, or Status...',
  'searchResponsePlaceholder': 'Search response...',
  'previousMatch': 'Previous match',
  'nextMatch': 'Next match',
  'found': 'found',
  'errorCopied': 'Error copied to clipboard',
  'goBack': 'GO BACK',
  'noRouteEvents': 'No route events yet',
  'navigateAround': 'Navigate around the app to see the flow',
  'liveNavigationStack': 'LIVE NAVIGATION STACK',
  'current': 'CURRENT',
  'step': 'Step {number}',
  'errorsCount': '{count} Errors',
  'errorsCountOne': '1 Error',
  'overlayHoldToOpen': 'hold to open',
  'overlayCollapse': 'Collapse',
  'overlayGrid': 'Grid',
  'overlayDash': 'Dash',
  'overlayReset': 'Reset',
  'overlayHide': 'Hide',
  'overlayFpsLabel': 'fps',
  'overlayApiLabel': 'API ',
  'overlayMemLabel': 'MEM ',
  'overlayNetLabel': 'NET ',
  'logsForScreen': 'LOGS FOR SCREEN',
  'diffRequestsLabel': 'diff',
};
