// GENERATED CODE - DO NOT MODIFY BY HAND

/// English translation map for the monitor dashboard.
const Map<String, String> enTranslations = {
  'tabTimeline': 'TIMELINE',
  'tabRequest': 'REQUEST',
  'tabResponse': 'RESPONSE',
  'tabHeaders': 'HEADERS',
  'initLabel': 'LOAD',
  'actionLabel': 'INTERACTION',
  'screensTitle': 'Screens',
  'allScreens': 'All Screens',
  'unknownScreen': 'Unknown Screen',
  'samples': 'samples',
  'fpsHistory': 'FPS HISTORY',
  'ramHistory': 'RAM HISTORY',
  'noApiCalls': 'No API calls yet',
  'onThisScreen': 'on this screen',
  'noErrors': 'No Flutter errors',
  'caughtYet': 'caught yet',
  'filterAll': 'ALL',
  'filterSlow': 'SLOW',
  'filterError': 'ERR',
  'searchPlaceholder': 'Search by URL, Method, or Status...',
  'searchResponsePlaceholder': 'Search response...',
  'previousMatch': 'Previous match',
  'nextMatch': 'Next match',
  'found': 'found',
  'errorCopied': 'Error copied to clipboard',
  'goBack': 'GO BACK',
  'noRouteEvents': 'No route events yet',
  'navigateAround': 'Navigate around the app to see the flow',
  'liveNavigationStack': 'LIVE NAVIGATION STACK',
  'current': 'CURRENT',
  'step': 'Step {number}',
  'errorsCount': '{count} Errors',
  'errorsCountOne': '1 Error',
  'overlayHoldToOpen': 'hold to open',
  'overlayCollapse': 'Collapse',
  'overlayGrid': 'Grid',
  'overlayDash': 'Dash',
  'overlayReset': 'Reset',
  'overlayHide': 'Hide',
  'overlayFpsLabel': 'fps',
  'overlayApiLabel': 'API ',
  'overlayMemLabel': 'MEM ',
  'overlayNetLabel': 'NET ',
  'logsForScreen': 'LOGS FOR SCREEN',
  'diffRequestsLabel': 'diff',
  'mapNoApiRequests': 'No API requests captured on this screen.',
  'mapNoMatchingApi': 'No matching API requests found.',
  'mapNoFlutterErrors': 'No Flutter errors captured on this screen.',
  'mapSubject': 'Interactive DevMonitor Flow Map',
  'mapBack': 'Back',
  'mapSwitchGrid': 'Switch to Grid Layout',
  'mapSwitchStream': 'Switch to Stream Layout',
  'mapSwitchCircular': 'Switch to Circular Layout',
  'mapSwitchTree': 'Switch to Tree Layout',
  'mapRecenterCamera': 'Recenter Camera',
  'mapSearchScreen': 'Search Screen',
  'mapExportWeb': 'Export Interactive Web Map',
  'mapHideGrid': 'Hide Background Grid',
  'mapShowGrid': 'Show Background Grid',
  'mapResetLayoutZoom': 'Reset Layout & Zoom',
  'mapExitFullScreen': 'Exit Full Screen',
  'mapFullScreen': 'Full Screen Preview',
  'mapZoomOut': 'Zoom Out',
  'mapZoomIn': 'Zoom In',
  'mapSearchTitle': 'Search Screen',
  'mapSearchHint': 'Enter screen name or route...',
  'mapSearchNotFound': 'No matching screen found',
  'mapApisCount': 'APIs ({filtered}/{total})',
  'mapVisitsCount': '{count} visits',
  'mapRequestsCount': '{count} requests',
};
