// GENERATED CODE - DO NOT MODIFY BY HAND

/// Vietnamese translation map for the monitor dashboard.
const Map<String, String> viTranslations = {
  'tabTimeline': 'TIMELINE',
  'tabRequest': 'REQUEST',
  'tabResponse': 'RESPONSE',
  'tabHeaders': 'HEADERS',
  'initLabel': 'KHỞI TẠO',
  'actionLabel': 'TƯƠNG TÁC',
  'screensTitle': 'Màn hình',
  'allScreens': 'Tất cả màn hình',
  'unknownScreen': 'Màn hình không xác định',
  'samples': 'mẫu',
  'fpsHistory': 'LỊCH SỬ FPS',
  'ramHistory': 'LỊCH SỬ RAM',
  'noApiCalls': 'Chưa có cuộc gọi API nào',
  'onThisScreen': 'trên màn hình này',
  'noErrors': 'Không có lỗi Flutter nào',
  'caughtYet': 'được ghi nhận',
  'filterAll': 'TẤT CẢ',
  'filterSlow': 'CHẬM',
  'filterError': 'LỖI',
  'searchPlaceholder': 'Tìm kiếm theo URL, Phương thức hoặc Trạng thái...',
  'searchResponsePlaceholder': 'Tìm kiếm phản hồi...',
  'previousMatch': 'Khớp trước',
  'nextMatch': 'Khớp sau',
  'found': 'tìm thấy',
  'errorCopied': 'Đã sao chép lỗi vào bộ nhớ tạm',
  'goBack': 'QUAY LẠI',
  'noRouteEvents': 'Chưa có sự kiện chuyển màn nào',
  'navigateAround': 'Di chuyển xung quanh ứng dụng để xem luồng chuyển màn',
  'liveNavigationStack': 'DANH SÁCH MÀN ĐANG MỞ (STACK)',
  'current': 'HIỆN TẠI',
  'step': 'Bước {number}',
  'errorsCount': '{count} Lỗi',
  'errorsCountOne': '1 Lỗi',
  'overlayHoldToOpen': 'nhấn giữ để mở',
  'overlayCollapse': 'Thu nhỏ',
  'overlayGrid': 'Lưới',
  'overlayDash': 'Dash',
  'overlayReset': 'Reset',
  'overlayHide': 'Ẩn',
  'overlayFpsLabel': 'fps',
  'overlayApiLabel': 'API ',
  'overlayMemLabel': 'MEM ',
  'overlayNetLabel': 'NET ',
  'logsForScreen': 'LOG CỦA MÀN HÌNH',
  'diffRequestsLabel': 'khác',
  'mapNoApiRequests': 'Không có log API nào trên màn hình này.',
  'mapNoMatchingApi': 'Không tìm thấy API nào khớp với tìm kiếm.',
  'mapNoFlutterErrors': 'Không có lỗi Flutter nào trên màn hình này.',
  'mapSubject': 'Sơ đồ luồng DevMonitor tương tác',
  'mapBack': 'Quay lại',
  'mapSwitchGrid': 'Chuyển sang dạng Lưới (Grid)',
  'mapSwitchStream': 'Chuyển sang dạng Luồng (Stream)',
  'mapSwitchCircular': 'Chuyển sang dạng Vòng (Circular)',
  'mapSwitchTree': 'Chuyển sang dạng Cây (Tree)',
  'mapRecenterCamera': 'Đưa camera về trung tâm',
  'mapSearchScreen': 'Tìm kiếm màn hình',
  'mapExportWeb': 'Xuất sơ đồ ra Web tương tác',
  'mapHideGrid': 'Ẩn lưới nền',
  'mapShowGrid': 'Hiện lưới nền',
  'mapResetLayoutZoom': 'Đặt lại bố cục & Thu phóng',
  'mapExitFullScreen': 'Thoát toàn màn hình',
  'mapFullScreen': 'Xem toàn màn hình',
  'mapZoomOut': 'Thu nhỏ',
  'mapZoomIn': 'Phóng to',
  'mapSearchTitle': 'Tìm kiếm màn hình',
  'mapSearchHint': 'Nhập tên màn hình hoặc route...',
  'mapSearchNotFound': 'Không tìm thấy màn hình phù hợp',
  'mapApisCount': 'APIs ({filtered}/{total})',
  'mapVisitsCount': '{count} lượt vào',
  'mapRequestsCount': '{count} requests',
};
