// GENERATED CODE - DO NOT MODIFY BY HAND

/// Vietnamese translation map for the monitor dashboard.
const Map<String, String> viTranslations = {
  'tabTimeline': 'TIMELINE',
  'tabRequest': 'REQUEST',
  'tabResponse': 'RESPONSE',
  'tabHeaders': 'HEADERS',
  'initLabel': 'KHỞI TẠO',
  'actionLabel': 'TƯƠNG TÁC',
  'screensTitle': 'Màn hình',
  'allScreens': 'Tất cả màn hình',
  'unknownScreen': 'Màn hình không xác định',
  'samples': 'mẫu',
  'fpsHistory': 'LỊCH SỬ FPS',
  'ramHistory': 'LỊCH SỬ RAM',
  'noApiCalls': 'Chưa có cuộc gọi API nào',
  'onThisScreen': 'trên màn hình này',
  'noErrors': 'Không có lỗi Flutter nào',
  'caughtYet': 'được ghi nhận',
  'filterAll': 'TẤT CẢ',
  'filterSlow': 'CHẬM',
  'filterError': 'LỖI',
  'searchPlaceholder': 'Tìm kiếm theo URL, Phương thức hoặc Trạng thái...',
  'searchResponsePlaceholder': 'Tìm kiếm phản hồi...',
  'previousMatch': 'Khớp trước',
  'nextMatch': 'Khớp sau',
  'found': 'tìm thấy',
  'errorCopied': 'Đã sao chép lỗi vào bộ nhớ tạm',
  'goBack': 'QUAY LẠI',
  'noRouteEvents': 'Chưa có sự kiện chuyển màn nào',
  'navigateAround': 'Di chuyển xung quanh ứng dụng để xem luồng chuyển màn',
  'liveNavigationStack': 'DANH SÁCH MÀN ĐANG MỞ (STACK)',
  'current': 'HIỆN TẠI',
  'step': 'Bước {number}',
  'errorsCount': '{count} Lỗi',
  'errorsCountOne': '1 Lỗi',
  'overlayHoldToOpen': 'nhấn giữ để mở',
  'overlayCollapse': 'Thu nhỏ',
  'overlayGrid': 'Lưới',
  'overlayDash': 'Dash',
  'overlayReset': 'Reset',
  'overlayHide': 'Ẩn',
  'overlayFpsLabel': 'fps',
  'overlayApiLabel': 'API ',
  'overlayMemLabel': 'MEM ',
  'overlayNetLabel': 'NET ',
  'logsForScreen': 'LOG CỦA MÀN HÌNH',
  'diffRequestsLabel': 'khác',
};
